server:
  port: 8081

logging:
  level:
    com.krev.notification_service: info

application:
  kafka:
    topic: "user.created"

spring:
  kafka:
    consumer:
      group-id: "notif-service"
      client-id: "demo-consumer"
      auto-offset-reset: earliest